# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: uwp_config
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'x86|x64|ARM'
- name: buildConfiguration
  value: 'Release'
- name: appxPackageDir
  value: '$(build.artifactStagingDirectory)\AppxPackages\\'
- name: Password
  value: $[variables.PfxPassword]
- name: NUGET_PACKAGES
  value: $(Pipeline.Workspace)/.nuget/packages

steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet
- task: NuGetCommand@2
  displayName: Run Nuget
  inputs:
    restoreSolution: '$(solution)'
- task: DownloadSecureFile@1
  name: signingCert
  displayName: 'Download CA certificate'
  inputs:
    secureFile: 'VtuberMusic-UWP_TemporaryKey.pfx'
- task: PowerShell@2
  displayName: Write Git Commit
  inputs:
    targetType: 'inline'
    script: |
      $Info = Get-Content "$(Build.Repository.LocalPath)/VtuberMusic-UWP/Properties/AssemblyInfo.cs"
              $Info = $Info -replace "GitCommit","$(Build.SourceVersion)"
              $Info = $Info -replace "Build.Count","$(Build.BuildNumber)"
              Set-Content -Path "$(Build.Repository.LocalPath)/VtuberMusic-UWP/Properties/AssemblyInfo.cs" -Value $Info
- task: VSBuild@1
  displayName: Build
  inputs:
    platform: 'x64'
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)" /p:AppxPackageDir="$(appxPackageDir)" /p:AppxBundle=Always /p:UapAppxPackageBuildMode=StoreUpload /p:PackageCertificateKeyFile="$(signingCert.secureFilePath)" /p:PackageCertificatePassword="$(Password)"'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.artifactstagingdirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: drop'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    publishLocation: 'pipeline'
    artifact: 'VtuberMusic_UWP'